In [1]:
%%javascript
(function(on) {
const e=$( "<a>Setup failed</a>" );
const ns="js_jupyter_suppress_warnings";
var cssrules=$("#"+ns);
if(!cssrules.length) cssrules = $("<style id='"+ns+"' type='text/css'>div.output_stderr { } </style>").appendTo("head");
e.click(function() {
    var s='Showing';  
    cssrules.empty()
    if(on) {
        s='Hiding';
        cssrules.append("div.output_stderr, div[data-mime-type*='.stderr'] { display:none; }");
    }
    e.text(s+' warnings (click to toggle)');
    on=!on;
}).click();
$(element).append(e);
})(true);

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn import linear_model
import random
import pylab
from scipy import stats
from sklearn.metrics import mean_absolute_error, mean_squared_error

C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):

In [3]:
df = pd.read_csv('CarPrice_Assignment.csv')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

Car_ID<br>
Unique id of each observation (Interger)

Symboling <br>
Its assigned insurance risk rating, A value of +3 indicates that the auto is risky, -3 that it is probably pretty safe.(Categorical) 

carCompany<br>
Name of car company (Categorical)

fueltype<br>
Car fuel type i.e gas or diesel (Categorical)

aspiration<br>
Aspiration used in a car (Categorical)

doornumber<br>
Number of doors in a car (Categorical)

carbody<br>
body of car (Categorical)

drivewheel<br>
type of drive wheel (Categorical)

enginelocation<br>
Location of car engine (Categorical)

wheelbase<br>
Weelbase of car (Numeric)

carlength<br>
Length of car (Numeric)

carwidth<br>
Width of car (Numeric)

carheight<br>
height of car (Numeric)

curbweight<br>
The weight of a car without occupants or baggage. (Numeric)

enginetype<br>
Type of engine. (Categorical)

cylindernumber<br>
cylinder placed in the car (Categorical)

enginesize<br>
Size of car (Numeric)

fuelsystem<br>
Fuel system of car (Categorical)

boreratio<br>
Boreratio of car (Numeric)

stroke<br>
Stroke or volume inside the engine (Numeric)

compressionratio<br>
compression ratio of car (Numeric)

horsepower<br>
Horsepower (Numeric)

peakrpm<br>
car peak rpm (Numeric)

citympg<br>
Mileage in city (Numeric)

highwaympg<br>
Mileage on highway (Numeric)

price(Dependent variable)<br>
Price of car (Numeric)

In [4]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 43.2+ KB

In [5]:
df.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [6]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [7]:
pd.Series(df.CarName).unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 4', 'mazda glc custom l', 'mazda glc custom',
       'buick electra 225 custom', 'buick century luxus (sw)',
       'buick century', 'buick skyhawk', 'buick opel isuzu deluxe',
       'buick skylark', 'buick century special',
       'buick regal sport coupe (turbo)', 'mercury cougar',
       'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander',
       'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero',
       'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue',
       'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke',
       'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz',
       'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks',
       'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl',
       'peugeot 505s turbo diesel', 'plymouth fury iii',
       'plymouth cricket', 'plymouth satellite custom (sw)',
       'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster',
       'porsche macan', 'porcshce panamera', 'porsche cayenne',
       'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e',
       'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz',
       'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia',
       'subaru tribeca', 'toyota corona mark ii', 'toyota corona',
       'toyota corolla 1200', 'toyota corona hardtop',
       'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii',
       'toyota corolla', 'toyota corolla liftback',
       'toyota celica gt liftback', 'toyota corolla tercel',
       'toyota corona liftback', 'toyota starlet', 'toyota tercel',
       'toyota cressida', 'toyota celica gt', 'toyouta tercel',
       'vokswagen rabbit', 'volkswagen 1131 deluxe sedan',
       'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)',
       'volkswagen super beetle', 'volkswagen dasher', 'vw dasher',
       'vw rabbit', 'volkswagen rabbit', 'volkswagen rabbit custom',
       'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245',
       'volvo 264gl', 'volvo diesel', 'volvo 246'], dtype=object)

Исправим опечатки и сокращения в названиях машин.

In [8]:
df.CarName = df.CarName.str.lower()

In [9]:
df['mark'] = df.CarName.map(lambda x: x.split()[0])
pd.Series(df.mark).unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [10]:
df.loc[(df.mark == 'maxda'), 'mark'] = 'mazda'
df.loc[(df.mark == 'porcshce'), 'mark'] = 'porsche'
df.loc[(df.mark == 'toyouta'), 'mark'] = 'toyota'
df.loc[(df.mark == 'vokswagen')|(df.mark == 'vw'), 'mark'] = 'volkswagen'
pd.Series(df.mark).unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'buick', 'mercury', 'mitsubishi',
       'nissan', 'peugeot', 'plymouth', 'porsche', 'renault', 'saab',
       'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

Для простоты уберем из названия модели тире и склеим все символы.

In [11]:
df['model'] = df.CarName.map(lambda x: str(''.join(x.split()[1:])).replace('-', ''))
pd.Series(df.model).unique()

array(['giulia', 'stelvio', 'quadrifoglio', '100ls', 'fox', '5000',
       '4000', '5000s(diesel)', '320i', 'x1', 'x3', 'z4', 'x4', 'x5',
       'impala', 'montecarlo', 'vega2300', 'rampage', 'challengerse',
       'd200', 'monaco(sw)', 'colthardtop', 'colt(sw)', 'coronetcustom',
       'dartcustom', 'coronetcustom(sw)', 'civic', 'civiccvcc',
       'accordcvcc', 'accordlx', 'civic1500gl', 'accord', 'civic1300',
       'prelude', 'civic(auto)', 'mux', 'dmax', 'dmaxvcross', 'xj', 'xf',
       'xk', 'rx3', 'glcdeluxe', 'rx2coupe', 'rx4', '626', 'glc', 'rx7gs',
       'glc4', 'glccustoml', 'glccustom', 'electra225custom',
       'centuryluxus(sw)', 'century', 'skyhawk', 'opelisuzudeluxe',
       'skylark', 'centuryspecial', 'regalsportcoupe(turbo)', 'cougar',
       'mirage', 'lancer', 'outlander', 'g4', 'mirageg4', 'montero',
       'pajero', 'versa', 'gtr', 'rogue', 'latio', 'titan', 'leaf',
       'juke', 'note', 'clipper', 'nv200', 'dayz', 'fuga', 'otti',
       'teana', 'kicks', '504', '304', '504(sw)', '604sl',
       '505sturbodiesel', 'furyiii', 'cricket', 'satellitecustom(sw)',
       'furygransedan', 'valiant', 'duster', 'macan', 'panamera',
       'cayenne', 'boxter', '12tl', '5gtl', '99e', '99le', '99gle', '',
       'dl', 'brz', 'baja', 'r1', 'r2', 'trezia', 'tribeca',
       'coronamarkii', 'corona', 'corolla1200', 'coronahardtop',
       'corolla1600(sw)', 'carina', 'markii', 'corolla',
       'corollaliftback', 'celicagtliftback', 'corollatercel',
       'coronaliftback', 'starlet', 'tercel', 'cressida', 'celicagt',
       'rabbit', '1131deluxesedan', 'model111', 'type3', '411(sw)',
       'superbeetle', 'dasher', 'rabbitcustom', '145e(sw)', '144ea',
       '244dl', '245', '264gl', 'diesel', '246'], dtype=object)

In [12]:
df.CarName = df[['mark', 'model']].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)
df.CarName.head()

0          alfa-romero giulia
1         alfa-romero stelvio
2    alfa-romero quadrifoglio
3                  audi 100ls
4                  audi 100ls
Name: CarName, dtype: object

In [13]:
df = df.drop(columns=['mark', 'model'])
df.drop_duplicates(inplace=True)
df.shape

(205, 26)

In [14]:
pd.Series(df.drivewheel).value_counts()

fwd    120
rwd     76
4wd      9
Name: drivewheel, dtype: int64

In [15]:
pd.Series(df.fueltype).value_counts()

gas       185
diesel     20
Name: fueltype, dtype: int64

In [16]:
pd.Series(df.aspiration).value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

In [17]:
pd.Series(df.carbody).value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: carbody, dtype: int64

In [18]:
pd.Series(df.fuelsystem).value_counts()

mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
spfi     1
mfi      1
Name: fuelsystem, dtype: int64

In [19]:
df['cylindernumber'].value_counts()

four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: cylindernumber, dtype: int64

Заменим категориальные значения на численные.

In [20]:
cylinders = {'two': 2, 'three': 3, 'four': 4, 'five': 5, 'six': 6, 'eight': 8, 'twelve': 12}
for key, value in cylinders.items():
    df.loc[(df.cylindernumber == key), 'cylindernumber'] = value
df.cylindernumber = df.cylindernumber.astype('int64')

In [21]:
df.cylindernumber

0      4
1      4
2      6
3      4
4      5
      ..
200    4
201    4
202    6
203    6
204    4
Name: cylindernumber, Length: 205, dtype: int64

Посмотрим корреляции между признаками, чтобы удалить признаки которые сильно друг с другом коррелируют.

In [22]:
df.corr()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
car_ID,1.000000,-0.151621,0.129729,0.170636,0.052387,0.255960,0.071962,-0.094493,-0.033930,0.260064,-0.160824,0.150276,-0.015006,-0.203789,0.015940,0.011255,-0.109093
symboling,-0.151621,1.000000,-0.531954,-0.357612,-0.232919,-0.541038,-0.227691,-0.113129,-0.105790,-0.130051,-0.008735,-0.178515,0.070873,0.273606,-0.035823,0.034606,-0.079978
wheelbase,0.129729,-0.531954,1.000000,0.874587,0.795144,0.589435,0.776386,0.339507,0.569329,0.488750,0.160959,0.249786,0.353294,-0.360469,-0.470414,-0.544082,0.577816
carlength,0.170636,-0.357612,0.874587,1.000000,0.841118,0.491029,0.877728,0.430672,0.683360,0.606454,0.129533,0.158414,0.552623,-0.287242,-0.670909,-0.704662,0.682920
carwidth,0.052387,-0.232919,0.795144,0.841118,1.000000,0.279210,0.867032,0.545007,0.735433,0.559150,0.182942,0.181129,0.640732,-0.220012,-0.642704,-0.677218,0.759325
carheight,0.255960,-0.541038,0.589435,0.491029,0.279210,1.000000,0.295572,-0.013995,0.067149,0.171071,-0.055307,0.261214,-0.108802,-0.320411,-0.048640,-0.107358,0.119336
curbweight,0.071962,-0.227691,0.776386,0.877728,0.867032,0.295572,1.000000,0.609727,0.850594,0.648480,0.168790,0.151362,0.750739,-0.266243,-0.757414,-0.797465,0.835305
cylindernumber,-0.094493,-0.113129,0.339507,0.430672,0.545007,-0.013995,0.609727,1.000000,0.846031,0.231399,0.008210,-0.020002,0.692016,-0.124172,-0.445837,-0.466666,0.718305
enginesize,-0.033930,-0.105790,0.569329,0.683360,0.735433,0.067149,0.850594,0.846031,1.000000,0.583774,0.203129,0.028971,0.809769,-0.244660,-0.653658,-0.677470,0.874145
boreratio,0.260064,-0.130051,0.488750,0.606454,0.559150,0.171071,0.648480,0.231399,0.583774,1.000000,-0.055909,0.005197,0.573677,-0.254976,-0.584532,-0.587012,0.553173
stroke,-0.160824,-0.008735,0.160959,0.129533,0.182942,-0.055307,0.168790,0.008210,0.203129,-0.055909,1.000000,0.186110,0.080940,-0.067964,-0.042145,-0.043931,0.079443
compressionratio,0.150276,-0.178515,0.249786,0.158414,0.181129,0.261214,0.151362,-0.020002,0.028971,0.005197,0.186110,1.000000,-0.204326,-0.435741,0.324701,0.265201,0.067984
horsepower,-0.015006,0.070873,0.353294,0.552623,0.640732,-0.108802,0.750739,0.692016,0.809769,0.573677,0.080940,-0.204326,1.000000,0.131073,-0.801456,-0.770544,0.808139
peakrpm,-0.203789,0.273606,-0.360469,-0.287242,-0.220012,-0.320411,-0.266243,-0.124172,-0.244660,-0.254976,-0.067964,-0.435741,0.131073,1.000000,-0.113544,-0.054275,-0.085267
citympg,0.015940,-0.035823,-0.470414,-0.670909,-0.642704,-0.048640,-0.757414,-0.445837,-0.653658,-0.584532,-0.042145,0.324701,-0.801456,-0.113544,1.000000,0.971337,-0.685751
highwaympg,0.011255,0.034606,-0.544082,-0.704662,-0.677218,-0.107358,-0.797465,-0.466666,-0.677470,-0.587012,-0.043931,0.265201,-0.770544,-0.054275,0.971337,1.000000,-0.697599
price,-0.109093,-0.079978,0.577816,0.682920,0.759325,0.119336,0.835305,0.718305,0.874145,0.553173,0.079443,0.067984,0.808139,-0.085267,-0.685751,-0.697599,1.000000

In [23]:
data = df.drop(columns=['car_ID', 'carlength', 'carwidth', 'carheight', 'curbweight', 'citympg', 'doornumber', 'enginelocation']).copy()

Переведем все категориальные признаки в бинарные.

In [24]:
datatypes = data.columns.to_series().groupby(df.dtypes).groups
datatypes

{int64: ['symboling', 'cylindernumber', 'enginesize', 'horsepower', 'peakrpm', 'highwaympg'], float64: ['wheelbase', 'boreratio', 'stroke', 'compressionratio', 'price'], object: ['CarName', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype', 'fuelsystem']}

In [25]:
ohe = OneHotEncoder()
for column in ['CarName', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype', 'fuelsystem']:
    column_ohe = ohe.fit_transform(data[[column]]).toarray()
    column_ohe_df = pd.DataFrame(column_ohe, columns = ohe.categories_[0])
    column_ohe_df.index = data.index
    data = data.join(column_ohe_df)

C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:395: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  check_array(X, dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_int = np.zeros((n_samples, n_features), dtype=np.int)
C:\Users\valer\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:111: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_mask = np.ones((n_samples, n_features), dtype=np.bool)

In [26]:
data = data.drop(columns=['CarName', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype', 'fuelsystem'])
data.head()

,symboling,wheelbase,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,highwaympg,...,ohcv,rotor,1bbl,2bbl,4bbl,idi,mfi,mpfi,spdi,spfi
0,3,88.6,4,130,3.47,2.68,9.0,111,5000,27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,3,88.6,4,130,3.47,2.68,9.0,111,5000,27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1,94.5,6,152,2.68,3.47,9.0,154,5000,26,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2,99.8,4,109,3.19,3.40,10.0,102,5500,30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2,99.4,5,136,3.19,3.40,8.0,115,5500,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

Обучим модель линейной регрессии.

In [27]:
model = linear_model.SGDRegressor(alpha = 0.01, max_iter = 1000)
X = data.drop(columns='price')
y = data.price

model.fit(X, y)

SGDRegressor(alpha=0.01, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [28]:
model.intercept_, model.coef_

(array([-5.02871766e+09]),
 array([ 3.64157617e+10, -1.19300074e+12, -1.43431056e+10, -2.91016680e+12,
        -3.79396651e+10, -4.03906130e+10, -7.43819921e+11, -1.61211915e+12,
        -2.05361383e+11, -9.15512249e+10,  5.65524607e+09, -1.80507296e+09,
        -2.46746110e+09,  3.61919126e+09,  3.71797440e+09, -3.48778285e+09,
        -8.64568791e+09, -1.83727720e+10, -3.45140762e+10,  4.12336821e+09,
         2.07649126e+10, -3.37843385e+09,  6.49013243e+09, -5.51694342e+09,
        -6.10803543e+09, -5.09424157e+09, -3.87317000e+08,  4.94060054e+08,
        -1.28641720e+10, -4.50444886e+09, -9.42060635e+09, -1.87260867e+09,
        -3.32892541e+09,  4.55590271e+09, -6.36882747e+09,  5.61769132e+09,
        -1.05861814e+09,  4.53494896e+09,  1.23109396e+10, -8.31795212e+08,
        -4.58694926e+09,  8.52251292e+09, -1.12081716e+10, -1.41542868e+09,
         2.24865961e+09,  3.13123963e+09,  1.15242697e+10,  1.32100580e+10,
         2.77465616e+09,  5.35735435e+09, -8.51233856e+09,  7.18609892e+09,
         4.39467004e+09,  1.14489718e+10,  1.44095140e+10,  8.54440581e+09,
        -5.89255343e+09,  6.38324417e+09, -4.27390820e+09,  2.21906244e+10,
        -1.06569472e+10, -1.24849365e+10, -7.01409220e+07,  8.55519947e+09,
         1.01517826e+10, -6.46303265e+09, -3.83725143e+09,  1.24035430e+10,
        -2.81449016e+09,  7.17774263e+09,  1.48607640e+10, -2.14508443e+08,
         3.64212854e+09, -8.95694519e+09,  7.75599313e+09, -2.10872836e+10,
         6.39824304e+09, -1.53591603e+10, -4.40672814e+09,  7.34820171e+09,
        -9.25858388e+09, -9.37345383e+09, -1.14105056e+10, -8.83096372e+09,
        -1.96760854e+09,  5.39390383e+09,  1.50889260e+09, -3.94214991e+09,
        -9.89336553e+09, -1.84352800e+09, -1.39360082e+09,  5.85596658e+09,
         1.71402386e+09,  3.25692817e+09,  5.33182280e+09, -4.13197375e+09,
        -1.36719370e+10, -3.64004935e+09,  1.31983390e+10,  9.92850498e+09,
         3.80342452e+09,  7.51174840e+09, -3.55717224e+09,  7.50118211e+09,
         1.98288838e+09, -1.95843574e+09,  1.40719734e+09, -9.45526118e+09,
        -1.41881998e+10, -9.17674791e+09, -2.94851513e+09,  1.36273669e+10,
        -1.51017143e+10,  1.37083415e+10,  1.12358237e+10,  2.85960171e+10,
         1.24196288e+10, -2.03597191e+09,  7.67206232e+09, -3.79448507e+09,
        -2.47660273e+09, -7.85874162e+09,  6.00709316e+09, -6.25677066e+09,
        -8.03445266e+09, -9.99233266e+09, -1.72418423e+10, -6.54230362e+07,
         5.37475545e+10, -7.04225344e+09, -4.88821204e+09,  2.41844269e+09,
        -7.42836311e+09, -3.63247058e+10, -8.34477981e+08,  1.54697701e+10,
         7.01328147e+09,  1.40926900e+09,  5.93460626e+09,  6.16386115e+09,
        -5.96202727e+09,  4.76424815e+09, -1.11808135e+10,  7.79991857e+08,
        -2.62655447e+09, -1.49376763e+10,  5.15946071e+09, -1.09573957e+09,
         8.14094023e+09, -1.24477698e+10,  1.69889794e+09, -5.85927956e+10,
         5.39209380e+10,  7.51862905e+10, -7.98581481e+10,  2.17088625e+09,
        -2.05017453e+10,  1.16836461e+10,  4.92230110e+09, -2.94694564e+09,
         1.45470072e+10,  5.56728888e+10, -7.48917536e+10,  3.71207117e+10,
         6.47970802e+09, -1.08300613e+10, -4.18414403e+10,  5.71112619e+10,
        -4.15470190e+10, -1.11650185e+10,  3.92481677e+10,  6.48505239e+10,
         1.31991793e+09, -5.85927956e+10, -8.31795212e+08, -4.08044284e+10,
        -1.31524400e+10,  3.29099219e+09]))

In [29]:
estimator = linear_model.LinearRegression()

In [30]:
estimator.fit(X, y)
estimator.intercept_, estimator.coef_

(-3009.374950880203,
 array([-1.60326171e+01,  3.24928486e+02, -3.74665738e+03,  1.91674701e+02,
        -2.96309413e+03, -1.89052239e+03, -1.86732374e+03, -5.34279728e+01,
         4.33540355e+00,  9.79550254e+01, -2.17629044e+03,  5.20058536e+03,
         8.28709558e+02,  1.48932509e+03,  7.90677735e+03,  4.61236665e+03,
         2.41842187e+03,  3.23197517e+02,  3.26709966e+02,  9.79687946e+03,
         1.13201995e+04,  8.50464473e+03,  1.90596447e+04,  1.29544416e+04,
         1.15331378e+04,  9.37108577e+03,  3.61606580e+03,  4.09031310e+03,
         8.98102438e+03,  1.54611889e+04,  8.31871358e+03,  1.73213263e+04,
         1.61574678e+03, -2.45586947e+03, -3.20890866e+03, -2.48893556e+03,
        -2.27394214e+03, -3.19094214e+03, -5.53213470e+03, -2.65920535e+03,
        -5.11612812e+03, -3.79166355e+03, -2.63693556e+03, -3.56912740e+03,
        -4.89993955e+03, -4.73984138e+03, -5.91668034e+03, -6.24624639e+02,
        -1.25101295e+03, -4.39143626e+03, -3.30227673e+03, -3.31123900e+03,
        -5.65844284e+03, -8.51376046e+02, -8.67408663e+02, -4.30102172e+03,
         5.81470838e+02, -2.71852916e+03,  2.28852446e+04, -1.82799472e+03,
        -5.95874115e+02,  1.14119429e+03, -1.53117694e+03, -4.66421613e+03,
        -1.28947514e+03, -6.20337035e+02, -1.53465186e+03, -2.32577987e+03,
         2.10707582e+03,  8.25221829e+02, -2.60070855e+03, -3.04425235e+03,
        -4.13811742e+03, -2.53178829e+03, -6.16815069e+03, -3.57262268e+03,
        -4.96815069e+03,  1.91215079e+03, -4.30255942e+03, -8.17786749e+02,
        -4.74251240e+03, -5.69808907e+02,  3.82520013e+03, -2.21181548e+03,
        -2.08681548e+03,  1.19795718e+03, -4.15576521e+03, -4.59642449e+03,
        -3.23778706e+03,  2.80851371e+03,  5.47957185e+02, -3.88681548e+03,
        -4.63204114e+03, -3.80260321e+02, -1.29647919e+03,  5.64322266e+02,
        -1.83834913e+03, -2.87245269e+03, -4.12948325e+03, -3.80733975e+03,
        -3.11236810e+03, -3.19094214e+03, -3.76203261e+03,  1.94758128e+04,
         1.89758107e+04,  7.58874646e+03,  1.74758107e+04, -2.66018506e+03,
        -3.59588592e+03,  3.52588847e+02,  1.93825223e+03, -1.17912271e+03,
        -7.68942427e+03, -7.10664849e+03, -4.81123580e+03, -4.95122742e+03,
        -6.13810764e+03, -7.77511012e+03, -5.04334570e+03, -4.12093510e+03,
         1.87887544e+03, -1.00903171e+03, -9.67687454e+03, -1.56496279e+03,
        -1.34284815e+03,  9.98875445e+02, -1.15432232e+03, -8.41986796e+03,
        -1.35033838e+03,  4.94774769e+02, -2.87760121e+03, -2.82286876e+03,
         3.84240093e+03, -5.92429166e+02, -3.99012287e+03,  2.52397735e+02,
        -4.91070352e+03, -4.39070352e+03, -3.94938658e+02, -1.37771373e+03,
        -1.86068195e+03,  4.79649752e+03,  1.09402096e+03, -4.69070352e+03,
        -1.58984526e+03, -4.28558747e+03, -1.91863805e+03,  7.09529872e+02,
         9.93422414e+03,  1.09207756e+03,  3.92154891e+03,  7.80456238e+03,
        -7.80456238e+03, -7.87777023e+02,  7.87777023e+02,  4.82037271e+02,
        -2.01796059e+03,  6.95560946e+02,  1.71256752e+03, -8.72205146e+02,
         3.95636555e+02, -5.70037896e+02,  1.74401341e+02,  1.70301349e+03,
         6.20104676e+03, -5.96706075e+03, -3.01355978e+03,  2.09035295e+03,
        -7.03176335e+00, -1.00676092e+03, -3.52319619e+02, -8.12461777e+02,
        -2.14795520e+03,  7.80456238e+03, -2.65920535e+03,  5.05690348e+00,
        -2.23861853e+03,  4.00941204e+02]))

In [31]:
y_predicted = estimator.predict(X)

print(f'MAE: {mean_absolute_error(y, y_predicted)}')
print(f'MSE: {mean_squared_error(y, y_predicted)}')
print(f'RMSE: {mean_squared_error(y, y_predicted) ** 0.5}')

MAE: 315.7434616685128
MSE: 333947.5542862761
RMSE: 577.8819553215658